name: Tests

on:
  push:
    branches:
      - main
    tags:
      - v[0-9].*
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    # TODO(btjanaka): Stop skipping pylint at some point in the future.
    env:
      SKIP: pylint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install all deps and pylint (to be available to pre-commit)
        run: pip install .[all] pylint
      - uses: pre-commit/action@v3.0.0
  test:
    strategy:
      max-parallel: 12 # All in parallel.
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # TODO(btjanaka): Enable all Python versions in the future.
        python-version: ["3.9"]
        # python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        exclude:
          # To cut down on runtime since Mac seems to take the longest.
          - os: macos-latest
            python-version: "3.8"
          - os: macos-latest
            python-version: "3.9"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install core deps
        run: pip install .[dev]
      - name: Test core
        run: >
          pytest tests
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps
        run: pip install .[visualize,dev]
      - name: Test coverage
        env:
          NUMBA_DISABLE_JIT: 1
        run: pytest tests
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps
        run: pip install .[visualize,dev]
      - name: Run benchmarks
        run: pytest -c pytest_benchmark.ini tests
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps
        run: pip install .[visualize]
      - name: Test Examples
        run: bash tests/examples.sh
  tutorials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps
        run: pip install .[visualize] jupyter nbconvert
      - name: Test Tutorials
        run: bash tests/tutorials.sh
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install deps
        run: pip install .[visualize,dev]
      - name: Build docs
        run: make docs
  deploy:
    runs-on: ubuntu-latest
    needs: [pre-commit, test, coverage, benchmarks, examples, tutorials]
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -e .
          pip install -e .[dev]
      - name: Publish
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          make release
